# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "12e866135c1a48077a819d6d70dcd041"
name = "ImageArmor Dev"
handle = "imagearmor-dev"
application_url = https://imagearmor--development.gadget.app/api/shopify/install-or-render"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, write_products"

[auth]
redirect_urls = [
  "https://imagearmor--development.gadget.app/api/connections/auth/shopify/callback"
]

[webhooks]
api_version = "2025-07"

[pos]
embedded = false
